logging.level:
  com.slack.api: ERROR
server:
  port: 3000
shop:
  email: "podlodkacast@gmail.com"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update