logging.level:
  com.slack.api: ERROR
server:
  port: 3001
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xx
    password: xx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true